on: push
name: 🚀 Desplegar Web
jobs:
  web-deploy:
    name: 🎉 Despliege
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.cluster031.hosting.ovh.net
        username: nervelp
        password: ${{ secrets.DESPLEGAR }}
